# Credenciales Mercado Pago (modo sandbox)
mercadopago.access.token=APP_USR-5269427771025073-092022-d3cf0287b689b942e82edd606c661780-3705479190

spring.datasource.url=jdbc:postgresql://localhost:5432/scout1
spring.datasource.username=postgres
spring.datasource.password=Charmander.123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082
