spring.application.name=backend-scout
# Conecta a la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/scout1
# ID  
spring.datasource.username=postgres
# Password
spring.datasource.password=Charmander.123
# Driver
spring.datasource.driver-class-name=org.postgresql.Driver
# Actualizador automatico de la base de datos, puede ser none, update, create, create-drop
spring.jpa.hibernate.ddl-auto=update
# Mostrador de consultas SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mejora en la legibilidad de las consultas SQL en consola postgres
spring.jpa.properties.hibernate.format_sql=true